version: '3.5'
services:
  proxy:
    image: nginx:latest
    networks:
      axolotl:
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - demo

  demo:
    image: registry.gitlab.com/axolotl.team/pikachu/demo/api:0.2.0
    networks:
      axolotl:
    command: server -p 5000

  porxy2:
    image: envoyproxy/envoy:latest
    networks:
      axolotl:
    ports:
      - target: 5001
        published: 5001
        protocol: tcp
    volumes:
      - type: bind
        source: ./envoy.yaml
        target: /etc/envoy/envoy.yaml
    depends_on:
      - demo
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml


networks:
  axolotl:
    external:
      name: axolotl
