name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: self-hosted
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    

      
    - name: ENV
      run: |
        cd ~
        echo $PWD
        ip address show enp0s3
        echo $PWD
        mkdir test
