name: Go

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  build:
    name: Build
    runs-on: self-hosted
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

      
    - name: ENV
      run: |
        echo ${{ github.event.head_commit.message }}
        echo ${{ github.event.head_commit.id }}
        echo ${{ github.event.head_commit.timestamp }}
        echo ${{ github.event.head_commit.author.name }}
        echo ${{ github.event.head_commit.author.email }}
        echo ${{ github.actor }}
        echo ${{ github.event.organization.login }}